/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a calculatorAdapter comWpAspServer.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "calculatorAdapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CalculatorAdaptor
 */

CalculatorAdaptor::CalculatorAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CalculatorAdaptor::~CalculatorAdaptor()
{
    // destructor
}

int CalculatorAdaptor::addition(int a, int b)
{
    // handle method call com.wp.asp.Calculator.addition
    int out0;
    QMetaObject::invokeMethod(parent(), "addition", Q_RETURN_ARG(int, out0), Q_ARG(int, a), Q_ARG(int, b));
    return out0;
}

double CalculatorAdaptor::divide(int a, int b)
{
    // handle method call com.wp.asp.Calculator.divide
    double out0;
    QMetaObject::invokeMethod(parent(), "divide", Q_RETURN_ARG(double, out0), Q_ARG(int, a), Q_ARG(int, b));
    return out0;
}

QString CalculatorAdaptor::helloWorld()
{
    // handle method call com.wp.asp.Calculator.helloWorld
    QString out0;
    QMetaObject::invokeMethod(parent(), "helloWorld", Q_RETURN_ARG(QString, out0));
    return out0;
}

int CalculatorAdaptor::multiply(int a, int b)
{
    // handle method call com.wp.asp.Calculator.multiply
    int out0;
    QMetaObject::invokeMethod(parent(), "multiply", Q_RETURN_ARG(int, out0), Q_ARG(int, a), Q_ARG(int, b));
    return out0;
}

int CalculatorAdaptor::subtraction(int a, int b)
{
    // handle method call com.wp.asp.Calculator.subtraction
    int out0;
    QMetaObject::invokeMethod(parent(), "subtraction", Q_RETURN_ARG(int, out0), Q_ARG(int, a), Q_ARG(int, b));
    return out0;
}

